---
# Deployment of our pac-sli-provider
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-sliprovider
  namespace: keptn
spec:
  selector:
    matchLabels:
      run: pac-sli-provider
  replicas: 1
  template:
    metadata:
      labels:
        run: pac-sli-provider
    spec:
      containers:
        - name: pac-sli-provider
          image: grabnerandi/pac-sliprovider:0.1.0 # Todo: Replace this with your image name
          ports:
            - containerPort: 8080
          env:
            - name: EVENTBROKER
              value: 'http://event-broker/keptn'
            - name: CONFIGURATION_SERVICE
              value: 'http://configuration-service:8080'
        - name: distributor
          image: keptn/distributor:0.7.1
          livenessProbe:
            httpGet:
              path: /health
              port: 10999
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PUBSUB_URL
              value: 'nats://keptn-nats-cluster'
            - name: PUBSUB_TOPIC
              value: 'sh.keptn.event.action.triggered'
            - name: PUBSUB_RECIPIENT
              value: '127.0.0.1'
---
# Expose pac-sli-provider via Port 8080 within the cluster
apiVersion: v1
kind: Service
metadata:
  name: pac-sli-provider
  namespace: keptn
  labels:
    run: pac-sli-provider
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    run: pac-sli-provider

